5gcamflow-1:
	number=0 ; while [ $$number -le 4 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-2:
	number=5 ; while [ $$number -le 9 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-3:
	number=10 ; while [ $$number -le 14 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-4:
	number=15 ; while [ $$number -le 19 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-5:
	number=20 ; while [ $$number -le 24 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-6:
	number=25 ; while [ $$number -le 30 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-7:
	number=30 ; while [ $$number -le 34 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-8:
	number=35 ; while [ $$number -le 40 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-9:
	number=41 ; while [ $$number -le 44 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-0:
	number=45 ; while [ $$number -le 49 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-11:
	number=50 ; while [ $$number -le 54 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-12:
	number=55 ; while [ $$number -le 59 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-13:
	number=60 ; while [ $$number -le 65 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

unicorn-camflow:
	number=0 ; while [ $$number -le 9 ] ; do \
		python parse.py -i ~/ds/unicorn/raw/$$number.txt -B ~/ds/unicorn/raw/base/base-$$number.txt -S ~/ds/unicorn/raw/stream/stream-$$number.txt ; \
		number=`expr $$number + 1` ; \
	done