5gcamflow-1:
	number=0 ; while [ $$number -le 4 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-2:
	number=5 ; while [ $$number -le 9 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-3:
	number=10 ; while [ $$number -le 14 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-4:
	number=15 ; while [ $$number -le 19 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-5:
	number=20 ; while [ $$number -le 24 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-6:
	number=25 ; while [ $$number -le 30 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-7:
	number=30 ; while [ $$number -le 32 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-8:
	number=70 ; while [ $$number -le 79 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-9:
	number=80 ; while [ $$number -le 89 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

5gcamflow-0:
	number=90 ; while [ $$number -le 96 ] ; do \
		python prepare.py -i ~/ds/camflow/30-04-2024/overlap/$$number -o preprocessed$$number.txt ; \
		python parse.py -i preprocessed$$number.txt -B ~/ds/camflow/30-04-2024/base/base-$$number.txt -S ~/ds/camflow/30-04-2024/stream/stream-$$number.txt ; \
		rm preprocessed$$number.txt ; \
		number=`expr $$number + 1` ; \
	done

unicorn-camflow:
	number=0 ; while [ $$number -le 9 ] ; do \
		python parse.py -i ~/ds/unicorn/raw/$$number.txt -B ~/ds/unicorn/raw/base/base-$$number.txt -S ~/ds/unicorn/raw/stream/stream-$$number.txt ; \
		number=`expr $$number + 1` ; \
	done